Repository platform-coop-toolkit/pinecone, pull requests merged in 2020-01, with the labels that each got.

#109 Fix focus inconsistencies (resolves #97)
  src/assets/scripts/Pinecone/FilterList/index.js
  src/assets/scripts/Pinecone/Menu/index.js
  src/components/01-atoms/10-tag-button/tag-button.njk
  src/components/02-molecules/00-menu/menu.config.js
  src/components/02-molecules/05-filter-list/filter-list.njk
Labels: enhancement

#111 Adds mobile filter overlay styles, improve typography and spacing
  src/assets/scripts/Pinecone/FilterList/index.js
  src/assets/scripts/Pinecone/MenuButton/index.js
  src/assets/styles/common/_global.scss
  src/assets/styles/common/_typography.scss
  src/assets/styles/components/_accordion.scss
  src/assets/styles/components/_breadcrumb.scss
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_disclosure-button.scss
  src/assets/styles/components/_filter-sort.scss
  src/assets/styles/components/_forms.scss
  src/assets/styles/components/_pagination.scss
  src/assets/styles/components/_tags.scss
  src/assets/styles/layouts/_archive.scss
  src/assets/styles/layouts/_page.scss
  src/components/01-atoms/09-button/button.config.js
  src/components/01-atoms/09-button/button.njk
  src/components/02-molecules/02-accordion/accordion.config.js
  src/components/02-molecules/02-accordion/accordion.njk
  src/components/02-molecules/05-filter-list/filter-list.njk
  src/components/03-layouts/01-page/page.njk
  src/components/03-layouts/02-archive/archive.njk
  src/components/_preview.njk
Labels: enhancement

#132 Add notifications (resolve #128)
  src/assets/images/success.svg
  src/assets/scripts/Pinecone/Notification/index.js
  src/assets/scripts/Pinecone/index.js
  src/assets/scripts/pinecone.js
  src/assets/styles/components/_notification.scss
  src/assets/styles/pinecone.scss
  src/components/01-atoms/01-icons/icons.config.js
  src/components/01-atoms/09-button/button.config.js
  src/components/01-atoms/09-button/button.njk
  src/components/02-molecules/06-notification/notification.config.js
  src/components/02-molecules/06-notification/notification.njk
Labels: enhancement

#133 Add single resource layout (resolves #122, resolves #126)
  src/assets/scripts/Pinecone/MenuButton/index.js
  src/assets/scripts/pinecone.js
  src/assets/styles/layouts/_archive.scss
  src/assets/styles/layouts/_header.scss
  src/assets/styles/layouts/_resource.scss
  src/assets/styles/mixins/_general.scss
  src/assets/styles/pinecone.scss
  src/components/02-molecules/00-menu-button/menu-button.config.js
  src/components/02-molecules/00-menu-button/menu-button.njk
  src/components/02-molecules/04-link-list/link-list.njk
  src/components/03-layouts/03-resource/resource.config.js
  src/components/03-layouts/03-resource/resource.njk
Labels: enhancement

#135 Fix button margins (resolves #134)
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_filter-sort.scss
  src/assets/styles/layouts/_resource.scss
Labels: enhancement

#136 Ensure images are in dist
  package.json
Labels: bug

#138 fix: Americanize favorite
  src/assets/images/favourite.svg
  src/components/01-atoms/01-icons/icons.config.js
  src/components/03-layouts/03-resource/resource.njk
Labels: enhancement

#139 feat(tooling): add commitlint
  .npmignore
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#137 fix: adjust top margin for unfiltered resource list
  src/assets/styles/layouts/_archive.scss
  src/components/03-layouts/02-archive/archive.config.js
  src/components/03-layouts/02-archive/archive.njk
Labels: bug

#145 fix: improve current/active/focus menu states (resolves #98)
  src/assets/styles/components/_menu--home.scss
  src/assets/styles/components/_menu.scss
Labels: bug

#146 fix: resolve specificity issue with banner background color
  src/assets/styles/layouts/_archive.scss
  src/assets/styles/layouts/_header.scss
  src/assets/styles/layouts/_page.scss
Labels: bug

#147 fix: make icon class names consistent with BEM syntax
  src/assets/styles/components/_menu.scss
  src/components/01-atoms/_svg/_svg.njk
Labels: bug

#148 feat: add language menu (resolves #67)
  src/assets/styles/components/_menu--home.scss
  src/assets/styles/components/_menu.scss
  src/components/01-atoms/_svg/_svg.config.js
  src/components/01-atoms/_svg/_svg.njk
  src/components/02-molecules/00-menu/menu.config.js
  src/components/02-molecules/00-menu/menu.njk
Labels: enhancement

#149 feat: add automatic publishing to GitHub Package Registry
  .github/workflows/publish-package.yml
Labels: enhancement

#154 feat: add disclosure button (resolves #150)
  src/assets/scripts/Pinecone/DisclosureButton/index.js
  src/assets/scripts/Pinecone/NestedCheckbox/index.js
  src/assets/scripts/Pinecone/index.js
  src/assets/scripts/pinecone.js
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_disclosure-button.scss
  src/assets/styles/components/_filter-sort.scss
  src/assets/styles/components/_icons.scss
  src/components/01-atoms/09-button/button.config.js
  src/components/01-atoms/09-button/button.njk
  src/components/01-atoms/11-disclosure-button/disclosure-button.config.js
  src/components/01-atoms/11-disclosure-button/disclosure-button.njk
  src/components/01-atoms/11-form-elements/10-inputs/inputs.config.js
  src/components/01-atoms/11-form-elements/10-inputs/inputs.njk
  src/components/01-atoms/11-form-elements/11-textareas/textareas.config.js
  src/components/01-atoms/11-form-elements/11-textareas/textareas.njk
  src/components/01-atoms/11-form-elements/12-selects/selects.config.js
  src/components/01-atoms/11-form-elements/12-selects/selects.njk
  src/components/01-atoms/11-form-elements/13-checkboxes/checkboxes.config.js
  src/components/01-atoms/11-form-elements/13-checkboxes/checkboxes.njk
  src/components/01-atoms/11-form-elements/14-radio-buttons/radio-buttons.config.js
  src/components/01-atoms/11-form-elements/14-radio-buttons/radio-buttons.njk
  src/components/01-atoms/11-form-elements/15-submit/submit.config.js
  src/components/01-atoms/11-form-elements/15-submit/submit.njk
  src/components/01-atoms/11-form-elements/_checkbox/_checkbox.config.js
  src/components/01-atoms/11-form-elements/_checkbox/_checkbox.njk
  src/components/01-atoms/11-form-elements/_input/_input.config.js
  src/components/01-atoms/11-form-elements/_input/_input.njk
  src/components/01-atoms/11-form-elements/_radio-button/_radio-button.config.js
  src/components/01-atoms/11-form-elements/_radio-button/_radio-button.njk
  src/components/01-atoms/11-form-elements/_select/_select.config.js
  src/components/01-atoms/11-form-elements/_select/_select.njk
  src/components/01-atoms/11-form-elements/_textarea/_textarea.config.js
  src/components/01-atoms/11-form-elements/_textarea/_textarea.njk
  src/components/02-molecules/05-filter-list/filter-list.njk
  src/components/02-molecules/08-disclosure-button/disclosure-button.config.js
  src/components/02-molecules/08-disclosure-button/disclosure-button.njk
Labels: enhancement

#155 feat: add saved search component (resolves #151)
  src/assets/styles/components/_saved-search.scss
  src/assets/styles/pinecone.scss
  src/components/02-molecules/09-saved-search/saved-search.config.js
  src/components/02-molecules/09-saved-search/saved-search.njk
Labels: enhancement

#158 fix: speed up disclosure icon animations
  src/assets/styles/components/_accordion.scss
  src/assets/styles/components/_disclosure-button.scss
  src/assets/styles/components/_menu.scss
Labels: enhancement

#157 feat: add banner brand (logo)
  src/assets/styles/components/_menu.scss
  src/assets/styles/layouts/_header.scss
  src/components/02-molecules/00-menu/menu.njk
  src/components/02-molecules/_brand/brand.config.js
  src/components/02-molecules/_brand/brand.njk
Labels: enhancement

#160 fix: allow search field to expand to full width
  src/assets/styles/components/_search.scss
Labels: bug

#165 feat: add inverse link and CTA variants
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_forms.scss
  src/assets/styles/components/_links.scss
  src/components/01-atoms/04-link/link.config.js
  src/components/01-atoms/04-link/link.njk
  src/components/01-atoms/06-call-to-action/call-to-action.config.js
Labels: enhancement

#164 feat: add search variant for home page (resolve #162)
  src/assets/styles/components/_search.scss
  src/components/02-molecules/07-search/search.config.js
  src/components/02-molecules/07-search/search.njk
Labels: enhancement

#170 feat: add home layout and info cards
  package.json
  src/assets/styles/common/_typography.scss
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_info-card.scss
  src/assets/styles/components/_link-list.scss
  src/assets/styles/components/_menu--home.scss
  src/assets/styles/components/_menu.scss
  src/assets/styles/components/_notification.scss
  src/assets/styles/components/_search.scss
  src/assets/styles/layouts/_footer.scss
  src/assets/styles/layouts/_header.scss
  src/assets/styles/layouts/_home.scss
  src/assets/styles/mixins/_general.scss
  src/assets/styles/pinecone.scss
  src/components/01-atoms/11-form-elements/14-radio-buttons/radio-buttons.njk
  src/components/02-molecules/00-menu/menu.config.js
  src/components/02-molecules/00-menu/menu.njk
  src/components/02-molecules/04-link-list/link-list.config.js
  src/components/02-molecules/04-link-list/link-list.njk
  src/components/02-molecules/06-notification/notification.njk
  src/components/02-molecules/10-info-card/info-card.config.js
  src/components/02-molecules/10-info-card/info-card.njk
  src/components/03-layouts/01-page/page.config.js
  src/components/03-layouts/02-archive/archive.config.js
  src/components/03-layouts/03-resource/resource.config.js
  src/components/03-layouts/04-home/home.config.js
  src/components/03-layouts/04-home/home.njk
  src/components/_preview.njk
Labels: enhancement

#176 feat: add footer (resolves #172)
  src/assets/images/logo.svg
  src/assets/styles/layouts/_footer.scss
  src/components/01-atoms/01-icons/icons.config.js
  src/components/01-atoms/_svg/_svg.njk
  src/components/02-molecules/00-menu/menu.njk
  src/components/02-molecules/11-footer/footer.config.js
  src/components/02-molecules/11-footer/footer.njk
  src/components/_preview.njk
Labels: enhancement

#183 feat: add favicon (resolve #181)
  fractal.js
  src/assets/images/favicon.png
  src/assets/images/favicon.svg
  src/components/_preview.njk
Labels: enhancement

#175 fix: language button label not accessible to screen readers
  src/assets/styles/components/_menu.scss
Labels: bug

#180 feat: add info and customize icons
  src/assets/images/customize.svg
  src/assets/images/info.svg
  src/components/01-atoms/01-icons/icons.config.js
  src/components/02-molecules/06-notification/notification.config.js
Labels: enhancement

#179 fix: improve home semantics
  src/assets/styles/common/_typography.scss
  src/assets/styles/common/typography/_blockquotes.scss
  src/assets/styles/common/typography/_headings.scss
  src/assets/styles/common/typography/_lists.scss
  src/assets/styles/common/typography/_paragraphs.scss
  src/assets/styles/common/typography/_utils.scss
  src/assets/styles/common/typography/_vertical-rhythm.scss
  src/assets/styles/components/_menu--home.scss
  src/assets/styles/layouts/_home.scss
  src/components/03-layouts/04-home/home.config.js
  src/components/03-layouts/04-home/home.njk
Labels: enhancement

#182 feat: add search bar to menu (resolves #178)
  src/assets/scripts/Pinecone/Menu/index.js
  src/assets/scripts/Pinecone/SearchToggle/index.js
  src/assets/scripts/Pinecone/index.js
  src/assets/scripts/pinecone.js
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_menu.scss
  src/assets/styles/components/_search.scss
  src/assets/styles/layouts/_header.scss
  src/components/02-molecules/00-menu/menu.config.js
  src/components/02-molecules/00-menu/menu.njk
  src/components/02-molecules/07-search/search.config.js
  src/components/_preview.njk
Labels: enhancement

#191 feat: add customize link to homepage feed (fixes #171)
  src/assets/styles/layouts/_home.scss
  src/components/03-layouts/04-home/home.njk
Labels: enhancement

#192 feat(tooling): add clean command, run prior to build
  package-lock.json
  package.json
Labels: enhancement

#194 feat: add filled variant of favorite icon
  src/assets/images/favorite-filled.svg
  src/components/01-atoms/01-icons/icons.config.js
Labels: enhancement

#195 feat: refactor type styles
  src/assets/styles/common/typography/_blockquotes.scss
  src/assets/styles/common/typography/_headings.scss
  src/assets/styles/common/typography/_lists.scss
  src/assets/styles/common/typography/_paragraphs.scss
  src/assets/styles/common/typography/_vertical-rhythm.scss
  src/components/01-atoms/02-typography/05-stack/stack.config.js
  src/components/01-atoms/02-typography/05-stack/stack.njk
  src/components/01-atoms/02-typography/06-repertoire/repertoire.config.js
  src/components/01-atoms/02-typography/06-repertoire/repertoire.njk
Labels: enhancement

#212 fix: restore functionality to nested checkboxes (resolves #210)
  src/assets/scripts/Pinecone/NestedCheckbox/index.js
Labels: bug

#215 docs: add minimal steps for incorporating Pinecone into a Django project
  README.md
Labels: documentation

#209 feat: improve card semantics (resolves #190)
  src/assets/images/favorite-filled.svg
  src/assets/styles/common/_todo.scss
  src/assets/styles/components/_buttons.scss
  src/assets/styles/components/_card.scss
  src/assets/styles/components/_menu.scss
  src/components/01-atoms/_separator/separator.njk
  src/components/02-molecules/01-card/card--resource.njk
  src/components/02-molecules/01-card/card.config.js
  src/components/02-molecules/01-card/card.njk
  src/components/03-layouts/02-archive/archive.config.js
Labels: enhancement

#218 feat: implement new call to action link styles (#201)
  src/assets/images/external.svg
  src/assets/styles/components/_call-to-action.scss
  src/assets/styles/pinecone.scss
  src/components/01-atoms/06-call-to-action/call-to-action.config.js
  src/components/01-atoms/06-call-to-action/call-to-action.njk
  src/components/03-layouts/03-resource/resource.njk
Labels: enhancement

#217 feat: add new format icons (resolves #211)
  src/assets/images/academic.svg
  src/assets/images/blog.svg
  src/assets/images/curriculum.svg
  src/assets/images/document.svg
  src/assets/images/save.svg
  src/assets/images/template.svg
  src/assets/styles/components/_card.scss
  src/components/01-atoms/01-icons/icons.config.js
  src/components/03-layouts/02-archive/archive.config.js
Labels: enhancement

#216 feat: add author icon to resource card (resolves #214)
  src/assets/images/author.svg
  src/assets/styles/common/_todo.scss
  src/components/01-atoms/01-icons/icons.config.js
  src/components/02-molecules/01-card/card--resource.njk
  src/components/02-molecules/01-card/card.njk
Labels: enhancement
